### ISSUE TITLE
simple local test-net using docker compose

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/test-infra#17] opened 2021-11-19 11:48 UTC
## Suggestion

Modify the existing approach in tendermint to run a local testnet using docker-compose.

References:

- https://github.com/tendermint/tendermint/blob/1c34d172406a01b94a1ea1b2917e1cea05275e46/Makefile#L248-L252
- https://github.com/tendermint/tendermint/blob/c4730bb46a0cde837bb93329420f99e7e6f151a9/docker-compose.yml

Instructions:
- https://docs.tendermint.com/v0.32/networks/docker-compose.html#build

It should be a low-hanging fruit to use this approach to spin up a celestia-node IMO. That way we create the genesis file once and put it directly into the docker containers before creating them (no need to scp stuff around etc).

**Comment by jbowen93** [comment] 2021-11-20 20:59
Why docker compose over an alternative automated environment setup? 

My preference would be to use a Kubernetes based environment with either [minikube](https://github.com/kubernetes/minikube), [k3s](https://github.com/k3s-io/k3s), or [Kind](https://github.com/kubernetes-sigs/kind) for a local cluster. This has the benefit of more closely resembling a production environment. I almost have a working setup on Minikube. It should be done by EOD Monday.

**Comment by liamsi** [comment] 2021-11-20 21:10
> Why docker compose over an alternative automated environment setup?

Mostly because it's probably way easier to spin up locally and does not require any additional dependencies for tools (at least on mac os docker compose is included in the docker bundle IIRC). Docker compose feels the most docker native and syntax is extremely simple and straight forward. Another reason is that we have a bunch of scripts and dockercompose file that could be used as the basis for this. 

But if you have sth with minikube almost working that is also perfectly fine with me 👌🏼 Kubernetes often felt like a bit of overkill to me, especially for local testing. The only project I really worked with kubernetes a bit was [keytransparency](https://github.com/google/keytransparency) and there we used kubernetes for cloud deployment but dockercompose for local testing. I thought that was still the most common way today.

**Comment by jbowen93** [comment] 2021-11-20 21:27
In general Kubernetes can be heavy weight for local testing. But if what we're testing is multiple containers networking between each other I think there are some advantages to the more robust configuration possibilities. 

Regarding the effort to spin up locally, `minikube` is a 68MB self contained go binary. Once it's spun up it is persistent until shutdown, so the startup time is amortized over all the necessary tests or deployments.

**Comment by liamsi** [comment] 2021-11-21 12:22
Makes sense. I think the only reservations I still have for kubernetes is that it cloud-native and doesn't necessarily have the best support for local development (and that was the main use-case my request was coming from for now).

Maybe these are non-issues:
- local deployment using kubernetes does not seem to have a local container registry? (annoying for local development testing as minikube constantly pushs/pulls images?)
- Cognitive overhead: most devs will know docker and docker-compose, while kubernetes is mostly only used in cloud settings (maybe some scripts can help with that).

**Comment by renaynay** [comment] 2021-11-22 09:39
I am against using kubes for testing infra generally as no one besides @jbowen93 can maintain it. There are > 3 people on the team that have worked with docker before in a more serious capacity, and docker is much easier to onboard to than kubes. 

If we decide to use kubes at all, it should be much later down the line when we have a more mature infra that demands something more serious like kubes to emulate a prod env, in which case we'll dedicate some engineering effort to it. Regardless, there are easier approaches to automation we can use like terraform or ansible.

I really want the the infra to be accessible to most devs on the team and kubes isn't quick or easy to use.

my 2c.

**Comment by jbowen93** [comment] 2021-12-15 20:44
I forgot that this issue existed. It's a duplicate of: https://github.com/celestiaorg/devops-test/issues/28 which I'll close in a little bit after writing some more documentation.

**Comment by jbowen93** [comment] 2021-12-22 04:39
https://github.com/celestiaorg/devops-test/issues/28 has been closed. So this issue should be closed.

**Closed** 2021-12-22 10:06 UTC
